version: '3.9'

services:
  db:
    image: postgres
    ports:
      - '7621:5432'
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER=postgres
    secrets:
      - postgres_password
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

secrets:
  postgres_password:
    file: ./secrets/postgres_password